apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: LoadBalancer  # Change this to NodePort or ClusterIP if needed
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: grafana
